---
- name: Launching EC2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
  - aws_cred.yaml
  roles:
  - ec2
- name: Configuring and Adding LoadBalancer to Instances
  hosts: localhost
  gather_facts: no
  vars_files:
  - aws_cred.yaml
  roles:
  - loadbalancer
