---
- name: Creating load balancer
  elb_classic_lb:
    name: "{{ lb }}"
    state: present
    aws_access_key: "{{ Access_key }}"
    aws_secret_key: "{{ Secret_key }}"
    aws_security_token: "{{ Security_token }}"
    region: "{{ region }}"
    subnets: "{{ subnet }}"
    wait: true
    cross_az_load_balancing: true
    scheme: internet-facing
    security_group_names: "{{ sg }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 81
- name: Adding instances to Loadbalancer
  elb_instance:
    aws_access_key: "{{ Access_key }}"
    aws_secret_key: "{{ Secret_key }}"
    aws_security_token: "{{ Security_token }}"
    instance_id: "{{ item }}"
    ec2_elbs: "{{ lb }}"
    state: present
    region: "{{ region }}"
    wait: true
    wait_timeout: 300
  loop: "{{ id }}"
