instance:
        - master
        - worker1
        - worker2
packages: boto3
region: us-east-1
vpc: vpc-05a81ece4f9c36050
subnet: subnet-0c9f97348f5ce35aa
sg: my_sg
ami_id: ami-00c39f71452c08778
keyname: vijay-keypair
instance_type: t2.micro
id: []
